version: "3.9"
services:

  eggshellver:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "10000:10000"
    image: yayuyokitano/golang:1.18.3-alpine3.16
    platform: linux/amd64
    #deploy:
      #restart_policy:
        #condition: on-failure

  db:
    image: postgres:14.4-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
