{
 "title": "Eggshellver",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eggshellver_authenticated_user_count",
     "legendFormat": "Registered"
    },
    { "expr": "eggshellver_cached_user_count", "legendFormat": "Cached" }
   ]
  },
  {
   "title": "Stats",
   "type": "stat",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "eggshellver_follow_count", "legendFormat": "Cached Follows" },
    { "expr": "eggshellver_playlist_count", "legendFormat": "Cached Playlists" },
    { "expr": "eggshellver_song_count", "legendFormat": "Cached Songs" },
    {
     "expr": "eggshellver_playlist_like_count",
     "legendFormat": "Liked Playlists"
    },
    { "expr": "eggshellver_track_like_count", "legendFormat": "Liked Tracks" }
   ]
  },
  {
   "title": "Authenticated Users",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "eggshellver_authenticated_user_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cached Follows",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "targets": [
    { "expr": "eggshellver_follow_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cached Playlists",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "targets": [
    { "expr": "eggshellver_playlist_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cached Likes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "targets": [
    { "expression": "$A+$B", "type": "math" }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(eggshellver_requests_received{method!=\"OPTIONS\"})",
     "legendFormat": "Made"
    },
    {
     "expr": "sum(eggshellver_requests_completed_count{method!=\"OPTIONS\"})",
     "legendFormat": "Completed"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(eggshellver_requests_errored[5m]))",
     "legendFormat": "Errored"
    },
    {
     "expr": "sum(rate(eggshellver_requests_completed_count{method!=\"OPTIONS\"}[5m]))",
     "legendFormat": "Successful"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(eggshellver_requests_completed_sum[5m])) / sum(rate(eggshellver_requests_completed_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Median request time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.5, eggshellver_requests_completed_sum{method!=\"OPTIONS\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "1st percentile request time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.01, eggshellver_requests_completed_sum{method!=\"OPTIONS\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max request time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(method, path) (eggshellver_requests_completed_sum{method!=\"OPTIONS\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "99th percentile request time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.99, eggshellver_requests_completed_sum{method!=\"OPTIONS\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(eggshellver_requests_errored[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "External Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(eggshellver_fetches{method!=\"OPTIONS\"})",
     "legendFormat": "Made"
    },
    {
     "expr": "sum(eggshellver_fetches_completed_count{method!=\"OPTIONS\"})",
     "legendFormat": "Completed"
    }
   ]
  },
  {
   "title": "External API Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 44 },
   "targets": [
    {
     "expr": "group(rate(eggshellver_fetches_errored[5m]))",
     "legendFormat": "Errored"
    },
    {
     "expr": "group(rate(eggshellver_fetches_completed_count[5m]))",
     "legendFormat": "Successful"
    }
   ]
  },
  {
   "title": "Average External API Response Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(eggshellver_fetches_completed_sum[5m])) / sum(rate(eggshellver_fetches_completed_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Median external API request time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.5, eggshellver_fetches_completed_sum{method!=\"OPTIONS\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "1st percentile external API request time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.01, eggshellver_fetches_completed_sum{method!=\"OPTIONS\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max external API request time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(path, method) (eggshellver_fetches_completed_sum{method!=\"OPTIONS\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "99th percentile external API request time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.99, eggshellver_fetches_completed_sum{method!=\"OPTIONS\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "External API Errors",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(eggshellver_fetches_errored[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}