version: 2
jobs:
  deploy:
    - image: cimg/base:2020.01
  steps:
    - run:
      name: Deploy
      command: |
        ssh -o StrictHostKeyChecking=no root@$EGGSHELLVER_HOST_IP "cd ./eggshellver && /bin/bash ./deploy.sh"


workflows:
  version: 2
  deploy:
    jobs:
      - approve:
          type: approval

      - deploy:
          context:
            - gowon
          requires:
            - approve