version: 2.1
jobs:
  deploy:
    machine:
      - enabled: true
    steps:
      - run:
          name: Fix ssh Could not resolve hostname
          command: |
            ssh-keyscan $EGGSHELLVER_HOST_IP >> ~/.ssh/known_hosts
      - add_ssh_keys:
          fingerprints:
            - "11:85:ef:3c:d8:66:58:d7:45:35:1b:2e:58:0c:2a:d8"
      - run:
          name: Deploy
          command: |
            ssh root@$EGGSHELLVER_HOST_IP "cd /root/eggshellver && /bin/bash ./deploy.sh"


workflows:
  version: 2.1
  deploy:
    jobs:
      - approve:
          type: approval

      - deploy:
          context:
            - gowon
          requires:
            - approve