version: 2.1
jobs:
  deploy:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run:
          name: Deploy
          command: |
            ssh -o StrictHostKeyChecking=no root@$EGGSHELLVER_HOST_IP "cd ./eggshellver && /bin/bash ./deploy.sh"


workflows:
  version: 2.1
  deploy:
    jobs:
      - approve:
          type: approval

      - deploy:
          context:
            - gowon
          requires:
            - approve